name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

# 新增权限配置
permissions:
  contents: write  # 必须显式授予写权限

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 关键！强制拉取主题子模块

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.7'  # 指定稳定版本
          extended: true

      - name: Build site
        run: |
          hugo \
            --environment production \
            --baseURL "https://xinchentechnote.github.io/note/" \
            --cleanDestinationDir \
            --minify

      - name: Debug public dir
        run: ls -R public  # 调试查看生成文件

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false